openapi: 3.0.1
info:
  title: Comuni ITA
  description: |-
    Semplice API che permette di ottenere in formato JSON i comuni italiani.
    
    *Logo ispired by: [Castle by Jasfart from the Noun Project](https://thenounproject.com/omataloon/)*
  version: 2.0.0
  x-logo: 
    url: "./assets/logo.png"
    altText: "Comuni ITA Logo"
  contact:
    name: Nicolò Rebaioli
    email: niko.reba@gmail.com
    url: https://rebaioli.altervista.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
externalDocs:
  description: Github
  url: https://github.com/Samurai016/comuni-ita
servers:
- url: https://comuni-ita.herokuapp.com
- url: http://comuni-ita.herokuapp.com
tags:
  - name: comuni
    description: Endpoint che restituiscono comuni
  - name: province
    description: Endpoint che restituiscono province
  - name: regioni
    description: Endpoint che restituiscono regioni
paths:
  /api/comuni:
    parameters:
      - $ref: '#/components/parameters/onlyname'
    get:
      summary: Ottieni la lista di tutti i comuni italiani.
      description: |-
        **Questo endpoint nelle versioni precedenti alla [2.0.0](https://github.com/Samurai016/Comuni-ITA/releases/tag/2.0.0) era disponibile all'url `/comune`.  \
        Ora quell'URL è deprecato, rimarrà disponibile, ma si consiglia l'aggiornamento dei propri progetti al nuovo URL.**
      operationId: comuni
      tags:
          - comuni
      responses:
        200:
          description: L'operazione ha avuto successo.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comune'
        5XX:
          description: Errore del server. **Contattare lo sviluppatore.**
  /api/comuni/{regione}:
    parameters:
      - $ref: '#/components/parameters/regione'
      - $ref: '#/components/parameters/onlyname'
    get:
      summary: Ottieni la lista di tutti i comuni della regione indicata.
      operationId: comuni-regione
      tags:
          - comuni
      responses:
        200:
          description: L'operazione ha avuto successo.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comune'
        400:
          description: Richiesta errata. Probabilmente uno dei parametri è errato.
        5XX:
          description: Errore del server. **Contattare lo sviluppatore.**
  /api/comuni/provincia/{provincia}:
    parameters:
      - $ref: '#/components/parameters/provincia'
      - $ref: '#/components/parameters/onlyname'
    get:
      summary: Ottieni la lista di tutti i comuni della provincia indicata.
      operationId: comuni-provincia
      tags:
          - comuni
      responses:
        200:
          description: L'operazione ha avuto successo.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comune'
        400:
          description: Richiesta errata. Probabilmente uno dei parametri è errato.
        5XX:
          description: Errore del server. **Contattare lo sviluppatore.**
  /api/province:
    get:
      summary: Ottieni la lista di tutte le province italiane.
      operationId: province
      tags:
          - province
      responses:
        200:
          description: L'operazione ha avuto successo.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "roma"
        5XX:
          description: Errore del server. **Contattare lo sviluppatore.**
  /api/province/{regione}:
    parameters:
      - $ref: '#/components/parameters/regione'
    get:
      summary: Ottieni la lista di tutte le province della regione indicata.
      operationId: province-regione
      tags:
          - province
      responses:
        200:
          description: L'operazione ha avuto successo.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "roma"
        400:
          description: Richiesta errata. Probabilmente uno dei parametri è errato.
        5XX:
          description: Errore del server. **Contattare lo sviluppatore.**
  /api/regioni:
    get:
      summary: Ottieni la lista delle regioni italiane.
      operationId: regioni
      tags:
          - regioni
      responses:
        200:
          description: L'operazione ha avuto successo.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "lazio"
        5XX:
          description: Errore del server. **Contattare lo sviluppatore.**
components:
  parameters:
    provincia:
      in: path
      name: provincia
      required: true
      schema:
        type: string
      description: |-
        Nome della provincia di cui si vogliono i dati.  
        Eventuali spazi o apostrofi vanno convertiti in notazione URL ([Link a W3Schools](https://www.w3schools.com/tags/ref_urlencode.ASP)).  
        [Qui per maggiori informazioni](https://github.com/Samurai016/Comuni-ITA/blob/master/README.md#province)
      example: "l%27aquila"
    regione:
      in: path
      name: regione
      required: true
      schema:
        type: string
      description: |-
        Nome della regione di cui si vogliono i dati.  
        Eventuali spazi o apostrofi vanno convertiti in notazione URL ([Link a W3Schools](https://www.w3schools.com/tags/ref_urlencode.ASP)).  
        [Qui per maggiori informazioni](https://github.com/Samurai016/Comuni-ITA/blob/master/README.md#regioni)
      example: "valle%20d%27aosta"
    onlyname:
      in: query
      name: onlyname
      schema:
        type: boolean
      description: |- 
        Può essere un valore qualunque.  
        In caso il parametro abbia un valore, il risultato della query sarà un array di stringhe, tali stringhe rappresentano i nomi dei comuni selezionati.
      example: true
  schemas:
    Comune:
      type: object
      properties:
        nome:
          type: string
          description: Nome del comune.
          example: "Roma"
        codice:
          type: string
          description: Codice ISTAT del comune.
          example: "058091"
        regione:
          type: string
          description: Regione del comune (in minuscolo).
          example: "lazio"
        provincia:
          type: string
          description: Provincia del comune (in minuscolo, per esteso).
          example: "roma"
        sigla:
          type: string
          description: Sigla della provincia del comune (in maiuscolo).
          example: "RM"
          pattern: "[A-Z]{2}"
        codiceCatastale:
          type: string
          description: Codice catastale del comune.
          example: "H501"
          pattern: "[A-Z]\\d{3}"
        cap:
          type: string
          description: Codice di Avviamento Postale (CAP) del comune.
          example: "00118"
          pattern: "\\d{5}" 
        coordinate:
          type: object
          properties:
            lat:
              type: number
              description: Latitudine
              example: 41.8954656
            lng:
              type: number
              description: Longitudine
              example: 12.4823243